Repository warmachine028/uemcrp, pull requests merged in 2022-09, with the labels that each got.

#43 Attendance Module 📇 #42
  client/src/App/index.jsx
  client/src/components/Auth/index.jsx
  client/src/components/Auth/styles.js
  client/src/components/Form/index.jsx
  client/src/components/Form/styles.js
  client/src/components/Input/index.jsx
  client/src/components/studentModules/Attendance/Ratings/index.jsx
  client/src/components/studentModules/Attendance/Ratings/styles.js
  client/src/components/studentModules/Attendance/index.jsx
  client/src/components/studentModules/Attendance/styles.js
Labels: ⭐ goal: addition, 💻 aspect: code, 🕹 aspect: interface, ✅ Completed, 🥗 status: ready for merge

#41 Logoutfix
  client/src/components/Navbar/styles.js
  package-lock.json
Labels: bug, 🛠 goal: fix, 🟩 priority: low, ✅ Completed, 🥗 status: ready for merge

#40 Invisible button refactored #38
  client/src/components/Navbar/styles.js
Labels: bug, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, ✅ Completed, 🥗 status: ready for merge

#46 Added Tweaks and Minor fixes for issues ✅📱🏡
  client/public/manifest.json
  client/src/App/index.jsx
  client/src/components/Auth/index.jsx
  client/src/components/Navbar/styles.js
  client/src/components/studentModules/AdmitCard/index.jsx
  client/src/components/studentModules/AdmitCard/styles.js
  client/src/components/studentModules/Attendance/index.jsx
  client/src/components/studentModules/ChangePassword/index.jsx
  client/src/components/studentModules/ChangePassword/styles.js
Labels: bug, ✨ goal: improvement, 💻 aspect: code, 🕹 aspect: interface, 🟧 priority: high, 🔒 staff only, 🛠 goal: fix, 🤖 aspect: dx, ✅ Completed, 🥗 status: ready for merge

#48 SaveAs Icon Added to Attendance Form
  client/src/components/studentModules/Attendance/index.jsx
Labels: enhancement, good first issue, ✨ goal: improvement, 🕹 aspect: interface, 🛠 goal: fix, ✅ Completed, 🥗 status: ready for merge

#52 Added fixes for Bills 💵
  client/package-lock.json
  client/package.json
  client/src/App/index.jsx
  client/src/components/studentModules/Attendance/index.jsx
  client/src/components/studentModules/Bills/List/index.jsx
  client/src/components/studentModules/Bills/List/styles.js
  client/src/components/studentModules/Bills/index.jsx
  client/src/components/studentModules/Bills/styles.js
  client/src/components/studentModules/Paymentdetails/index.jsx
  client/src/components/studentModules/index.js
  client/src/data/bills.js
  client/src/data/dashboard.js
Labels: ⭐ goal: addition, 💻 aspect: code, ✅ Completed, 🥗 status: ready for merge

#55 Added fixes for Download ADMIT Cards 🌟🌟🌟🌟
  client/package-lock.json
  client/package.json
  client/src/components/studentModules/AdmitCard/Card/index.jsx
  client/src/components/studentModules/AdmitCard/index.jsx
  client/src/data/users.js
  server/.gitignore
Labels: ✨ goal: improvement, 💻 aspect: code, 🕹 aspect: interface, 🟧 priority: high, 🔒 staff only, 🛠 goal: fix, ✅ Completed, 🥗 status: ready for merge

#59 Removed the tooltip from RECESS column
  client/src/components/TimeTable/index.jsx
Labels: bug, 💻 aspect: code, 🟧 priority: high, 🛠 goal: fix, ✅ Completed, 🥗 status: ready for merge

#60 [CHORE]: Updated Readme with new images
  README.md
  assets/ipad.png
  assets/ipad_login.png
  assets/macbook.png
  assets/mobile.png
Labels: documentation, ✨ goal: improvement, ⭐ goal: addition, 📄 aspect: text, 🟧 priority: high, 🥗 status: ready for merge

#62 Add date picker for organisational calendar component
  client/package-lock.json
  client/package.json
  client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/index.jsx
  client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/styles.js
  client/src/components/studentModules/OrganisationalCalander/index.jsx
Labels: ⭐ goal: addition, 💻 aspect: code, 🕹 aspect: interface, 🟧 priority: high, ✅ Completed, 🥗 status: ready for merge

#68 Uemcrp test
  rules/SETUP.md
Labels: documentation, ⛔️ status: discarded, ✨ goal: improvement, ⭐ goal: addition, 🟩 priority: low, 🥗 status: ready for merge
