Repository warmachine028/uemcrp, pull requests merged in 2022-08, with the labels that each got.

#12 Fixes for Unresponsive Home Page #10
  client/src/App/index.jsx
  client/src/components/Auth/index.jsx
  client/src/components/Dashboard/index.jsx
  client/src/components/Dashboard/styles.js
  client/src/components/Home/index.jsx
  client/src/components/Home/styles.js
  client/src/components/Navbar/index.jsx
  client/src/components/TimeTable/index.jsx
  client/src/components/TimeTable/styles.js
  client/src/data/dashboard.js
  client/src/data/notices.js
  client/src/data/timeTables.js
  client/src/data/users.js
Labels: 🟨 priority: medium, 🛠 goal: fix, ✅ Completed, 🥗 status: ready for merge

#14 PlaceHolder text
  client/src/components/Auth/index.jsx
Labels: 🟨 priority: medium, 🛠 goal: fix, ✅ Completed, 🥗 status: ready for merge

#15 Added Fix for Faulty PR #14
  client/src/components/Auth/index.jsx
Labels: 💻 aspect: code, 🛠 goal: fix, ✅ Completed, 🥗 status: ready for merge

#25 added fixes for #19
  client/src/App/index.jsx
  client/src/components/studentModules/Attendance/index.jsx
  client/src/components/studentModules/OrganisationalCalander/index.jsx
  client/src/components/studentModules/Payduefees/index.jsx
  client/src/components/studentModules/Paymentdetails/index.jsx
  client/src/components/studentModules/UnitTestDetails/index.jsx
  client/src/components/studentModules/UniversityMarkingSystem/index.jsx
  client/src/components/studentModules/UpdateInfo/index.jsx
  client/src/components/studentModules/index.js
Labels: ⭐ goal: addition, 💻 aspect: code, ✅ Completed, 🥗 status: ready for merge

#27 Added Auth Design in Figma for fixes in #5
  README.md
Labels: 🛠 goal: fix, 🤖 aspect: dx, ✅ Completed, 🥗 status: ready for merge

#17 Title and logo are updated
  client/package-lock.json
  client/public/index.html
  client/public/logo.png
Labels: ⭐ goal: addition, 🕹 aspect: interface, 🛠️ status: under development

#36 Admit cards mobile responsive
  client/src/components/Navbar/styles.js
  client/src/components/studentModules/AdmitCard/Card/index.jsx
  client/src/components/studentModules/AdmitCard/Card/styles.js
  client/src/components/studentModules/AdmitCard/styles.js
Labels: good first issue, ✨ goal: improvement, 🕹 aspect: interface, 🟧 priority: high, 🛠 goal: fix, ✅ Completed, 🥗 status: ready for merge
