Repository warmachine028/uemcrp, pull requests merged in 2022-10, with the labels that each got.

#73 Removed name field from paper component
  client/src/components/Home/index.jsx
Labels: hacktoberfest-accepted, 🥗 status: ready for merge

#74 made responsive calendar
  client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/index.jsx
Labels: hacktoberfest-accepted, 🥗 status: ready for merge

#75 added header for selecting semester and table for showing score
  client/package-lock.json
  client/package.json
  client/src/components/studentModules/UniversityMarkingSystem/List/index.jsx
  client/src/components/studentModules/UniversityMarkingSystem/List/styles.js
  client/src/components/studentModules/UniversityMarkingSystem/index.jsx
  client/src/components/studentModules/UniversityMarkingSystem/styles.js
Labels: ⭐ goal: addition, 💻 aspect: code, 🕹 aspect: interface, hacktoberfest, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#82 Add : Reset date button
  client/src/components/studentModules/Bills/index.jsx
  client/src/components/studentModules/Bills/styles.js
Labels: ⭐ goal: addition, hacktoberfest, 🟩 priority: low, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#78 Added Responsiveness to PayDues Page
  client/src/App/styles.js
  client/src/components/studentModules/Payduefees/index.jsx
  client/src/components/studentModules/Payduefees/styles.js
Labels: bug, enhancement, 🕹 aspect: interface, 🟧 priority: high, 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#85 UniversityMarkingSystem UI Fixes
  client/src/components/studentModules/UniversityMarkingSystem/List/styles.js
  client/src/components/studentModules/UniversityMarkingSystem/index.jsx
  client/src/components/studentModules/UniversityMarkingSystem/styles.js
Labels: 🚦 status: awaiting triage, 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#95 bug fixed date reset button working
  client/src/components/studentModules/Bills/index.jsx
Labels: ✨ goal: improvement, ⭐ goal: addition, 💻 aspect: code, 🟨 priority: medium, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#94 Add build test to workflow
  .github/workflows/build.yaml
  client/package.json
Labels: 💻 aspect: code, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#96 Updated the Unit Test Details
  client/src/components/studentModules/UnitTestDetails/List/index.jsx
  client/src/components/studentModules/UnitTestDetails/List/styles.js
  client/src/components/studentModules/UnitTestDetails/index.jsx
  client/src/components/studentModules/UnitTestDetails/styles.js
  client/src/data/unittest.js
  client/src/data/users.js
Labels: enhancement, ⭐ goal: addition, 🕹 aspect: interface, hacktoberfest, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#98 added smaller font size for mobile view
  client/src/components/studentModules/Payduefees/index.jsx
  client/src/components/studentModules/Payduefees/styles.js
Labels: bug, 🕹 aspect: interface, hacktoberfest, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#101 SideBar in calendar organisation
  client/src/App/styles.js
  client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/index.jsx
  client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/styles.js
  client/src/components/studentModules/OrganisationalCalander/SideBar/index.jsx
  client/src/components/studentModules/OrganisationalCalander/SideBar/styles.js
  client/src/components/studentModules/OrganisationalCalander/index.jsx
  client/src/data/holidays.js
  client/src/index.css
Labels: enhancement, ✨ goal: improvement, ⭐ goal: addition, 🕹 aspect: interface, hacktoberfest, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#103 Feat/captcha
  client/package.json
  client/src/components/Auth/index.jsx
  client/src/components/Auth/styles.js
Labels: enhancement, 🕹 aspect: interface, hacktoberfest, 🟥 priority: critical, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#104 User Image Update Feature
  client/src/components/Home/index.jsx
  client/src/components/Home/styles.js
  client/src/images/camera.svg
Labels: ✨ goal: improvement, ⭐ goal: addition, 🕹 aspect: interface, 🟧 priority: high, hacktoberfest, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#107 Making the grid items clickable only when hovering over the pictures
  client/src/components/Dashboard/index.jsx
  client/src/components/Dashboard/styles.js
Labels: ✨ goal: improvement, 🕹 aspect: interface, hacktoberfest, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#109 profile pic cursor-some unwanted lines of codes cleared in dashboard
  client/src/components/Dashboard/index.jsx
  client/src/components/Home/index.jsx
  client/src/components/Home/styles.js
Labels: bug, 🛠 goal: fix, hacktoberfest, 🟩 priority: low, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#113 calendar enhancement
  client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/index.jsx
  client/src/components/studentModules/OrganisationalCalander/SideBar/index.jsx
  client/src/components/studentModules/OrganisationalCalander/index.jsx
Labels: enhancement, ✨ goal: improvement, 💻 aspect: code, 🟧 priority: high, hacktoberfest, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge

#112 Fixed the console errors and removed console logs in client app
  client/src/components/studentModules/UnitTestDetails/List/index.jsx
  client/src/components/studentModules/UnitTestDetails/index.jsx
Labels: bug, enhancement, ✨ goal: improvement, 💻 aspect: code, hacktoberfest, 🟩 priority: low, hacktoberfest-accepted, ✅ Completed, 🥗 status: ready for merge
